# Book settings
title: "SCU Lab course: Image Analysis"
author: Marvin Albert
copyright: "2025 ETH Zurich"
logo: 'logo.webp'
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default! See here: https://jupyterbook.org/en/stable/customize/config.html
    - html_image