name: Test Notebooks

on:
  push:
    branches:
      - "2026"
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:
      - "2026"
  workflow_dispatch:

jobs:
  test:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.platform }}
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
      - uses: prefix-dev/setup-pixi@v0.9.6
        with:
          pixi-version: v0.70.2
          cache: true

      - name: Run tests
        run: pixi run test
